# Generated by Django 3.1.5 on 2021-02-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='amazonProductPagesScrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('productID', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.CharField(blank=True, max_length=512, null=True)),
                ('response_dir', models.CharField(blank=True, max_length=200, null=True)),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
    ]
