# Generated by Django 3.1.5 on 2021-02-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0003_auto_20210223_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazonproductpagesscrapper',
            name='language',
            field=models.CharField(default='English', max_length=20),
        ),
    ]
