# Generated by Django 3.1.5 on 2021-02-28 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0004_amazonproductpagesscrapper_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='productDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributes', models.CharField(blank=True, max_length=200, null=True)),
                ('values', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='productPagesScrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('productID', models.CharField(blank=True, max_length=50, null=True)),
                ('title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('title_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('description_en', models.BooleanField(default=False)),
                ('description_ar', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='amazonProductDetails',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='productID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrapper.productpagesscrapper'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='productID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrapper.productpagesscrapper'),
        ),
        migrations.DeleteModel(
            name='amazonProductPagesScrapper',
        ),
    ]
