# Generated by Django 3.1.5 on 2021-02-28 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0005_auto_20210228_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpagesscrapper',
            name='category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='productHighlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlight', models.CharField(blank=True, max_length=512, null=True)),
                ('productID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrapper.productpagesscrapper')),
            ],
        ),
    ]
