# Generated by Django 3.1.5 on 2021-03-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0006_auto_20210228_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producthighlights',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productimages',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
