# Generated by Django 3.1.5 on 2021-03-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0007_auto_20210301_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpagesscrapper',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
