# Generated by Django 3.1.5 on 2021-03-10 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0008_productpagesscrapper_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='productDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('productID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrapper.productpagesscrapper')),
            ],
        ),
    ]
