# Generated by Django 3.1.5 on 2021-03-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0009_productdescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthighlights',
            name='highlight',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
