# Generated by Django 3.1.5 on 2021-03-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0010_auto_20210310_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='attributes',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='values',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
