# Generated by Django 3.1.5 on 2021-03-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0011_auto_20210310_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimages',
            name='language',
        ),
    ]
