# Generated by Django 3.1.5 on 2021-03-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0013_auto_20210316_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producthighlights',
            name='highlight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
