# Generated by Django 3.1.5 on 2021-05-17 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0014_auto_20210316_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='variationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_asin', models.CharField(blank=True, max_length=50, null=True)),
                ('current_asin', models.CharField(blank=True, max_length=50, null=True)),
                ('dimension', models.CharField(blank=True, max_length=50, null=True)),
                ('dimension_val', models.TextField(blank=True, null=True)),
                ('title_en', models.CharField(blank=True, max_length=200, null=True)),
                ('title_ar', models.CharField(blank=True, max_length=200, null=True)),
                ('images', models.TextField(blank=True, null=True)),
                ('description_en', models.BooleanField(default=False)),
                ('description_ar', models.BooleanField(default=False)),
                ('productID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrapper.productpagesscrapper')),
            ],
        ),
    ]
