# Generated by Django 3.1.5 on 2021-05-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0016_auto_20210518_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationsettings',
            name='dimension_val_ar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
