# Generated by Django 3.1.5 on 2021-05-18 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0017_variationsettings_dimension_val_ar'),
    ]

    operations = [
        migrations.CreateModel(
            name='totalVariations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_asin', models.CharField(blank=True, max_length=50, null=True)),
                ('name_en', models.CharField(blank=True, max_length=50, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=50, null=True)),
                ('value_en', models.CharField(blank=True, max_length=50, null=True)),
                ('value_ar', models.CharField(blank=True, max_length=50, null=True)),
                ('productID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrapper.productpagesscrapper')),
            ],
        ),
    ]
