# Generated by Django 3.1.5 on 2021-06-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0020_fc_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='variationsettings',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
