# Generated by Django 3.1.5 on 2021-07-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0022_auto_20210606_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpagesscrapper',
            name='old_price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productpagesscrapper',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
