# Generated by Django 3.2.4 on 2021-08-30 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0025_auto_20210717_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fc_grades',
            options={'verbose_name_plural': 'FC_Grades'},
        ),
        migrations.AlterModelOptions(
            name='productdescription',
            options={'verbose_name_plural': 'Product Description'},
        ),
        migrations.AlterModelOptions(
            name='productdetails',
            options={'verbose_name_plural': 'Product Details'},
        ),
        migrations.AlterModelOptions(
            name='producthighlights',
            options={'verbose_name_plural': 'Product Highlights'},
        ),
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='productpagesscrapper',
            options={'verbose_name_plural': 'Product Pages Scrapper'},
        ),
        migrations.AlterModelOptions(
            name='totalvariations',
            options={'verbose_name_plural': 'Total Variations'},
        ),
        migrations.AlterModelOptions(
            name='variationsettings',
            options={'verbose_name_plural': 'Variation Settings'},
        ),
    ]
