# Generated by Django 3.2.4 on 2021-09-09 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0026_auto_20210830_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdescription',
            name='productID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapper.productpagesscrapper'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='productID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapper.productpagesscrapper'),
        ),
        migrations.AlterField(
            model_name='producthighlights',
            name='productID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapper.productpagesscrapper'),
        ),
        migrations.AlterField(
            model_name='productimages',
            name='productID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapper.productpagesscrapper'),
        ),
        migrations.AlterField(
            model_name='totalvariations',
            name='productID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapper.productpagesscrapper'),
        ),
        migrations.AlterField(
            model_name='variationsettings',
            name='productID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrapper.productpagesscrapper'),
        ),
    ]
