# Generated by Django 3.2.4 on 2021-09-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0027_auto_20210909_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpagesscrapper',
            name='title_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='productpagesscrapper',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='variationsettings',
            name='title_ar',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='variationsettings',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
