# Generated by Django 3.2.4 on 2021-11-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0028_auto_20210919_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpagesscrapper',
            name='batchname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
