# Generated by Django 3.2.4 on 2022-01-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0030_auto_20211120_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='values',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
