# Generated by Django 3.2.4 on 2022-01-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0031_alter_productdetails_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='values',
            field=models.CharField(blank=True, max_length=3072, null=True),
        ),
    ]
