# Generated by Django 3.2.4 on 2022-05-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0034_alter_productpagesscrapper_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpagesscrapper',
            name='productID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
